/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SearchAlgorithm;

import java.awt.event.KeyEvent;
import java.io.PrintStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Minato
 */
public class FrontEndSearch extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(FrontEndSearch.class.getName());
    private PrintStream standardOut;

    /**
     * Creates new form FrontEndSearch
     */
    public FrontEndSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        openPathFile = new javax.swing.JTextField();
        savePathFile = new javax.swing.JTextField();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        modifyPrice = new javax.swing.JButton();
        reductionPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayResult = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Search Pro");

        jLabel2.setText("Minato");

        openPathFile.setEditable(false);
        openPathFile.setBackground(new java.awt.Color(204, 204, 255));

        savePathFile.setEditable(false);
        savePathFile.setBackground(new java.awt.Color(204, 204, 255));

        openFileButton.setText("...");
        openFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openFileButton.setBorderPainted(false);
        openFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        saveFileButton.setText("...");
        saveFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveFileButton.setBorderPainted(false);
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });

        modifyPrice.setText("Chỉnh Giá");
        modifyPrice.setActionCommand("Chỉnh giá");
        modifyPrice.setAlignmentY(0.0F);
        modifyPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modifyPrice.setBorderPainted(false);
        modifyPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPriceActionPerformed(evt);
            }
        });

        reductionPrice.setBackground(new java.awt.Color(255, 204, 255));
        reductionPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reductionPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reductionPrice.setToolTipText("Chọn giá cần giảm");
        reductionPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reductionPriceActionPerformed(evt);
            }
        });
        reductionPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reductionPriceKeyTyped(evt);
            }
        });

        jLabel3.setText("VNĐ");

        jLabel4.setText("Giảm");

        Close.setText("Đóng");
        Close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Close.setBorderPainted(false);
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        displayResult.setEditable(false);
        displayResult.setColumns(20);
        displayResult.setRows(5);
        displayResult.setToolTipText("This is log");
        displayResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(displayResult);

        jLabel5.setText("Lưu sản phẩm lỗi:");

        jLabel6.setText("Mở tệp sản phẩm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openPathFile, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(savePathFile))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(modifyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reductionPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 290, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFileButton)
                    .addComponent(openPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFileButton)
                    .addComponent(savePathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reductionPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPriceActionPerformed
        // TODO add your handling code here:
        if (openPathFile.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn đường dẫn đến tệp sản phẩm!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (savePathFile.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn đường dẫn lưu sản phẩm chưa chỉnh được giá!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (reductionPrice.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập giá cần giảm!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int priceReduction = Integer.parseInt(reductionPrice.getText());

        if (priceReduction < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn giá cần giảm > 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        modifyPrice.setText("Đang xử lý");
        modifyPrice.setEnabled(false);

        PrintStream printStream = new PrintStream(new CustomOutputStream(displayResult));
//        try {
//            printStream = new PrintStream(new CustomOutputStream(displayResult), true, "UTF-8");
//        } catch (UnsupportedEncodingException ex) {
//            Logger.getLogger(FrontEndSearch.class.getName()).log(Level.SEVERE, null, ex);
//        }
        // Keeps reference of standard output stream
        standardOut = System.out;
        // Re-assigns standard output stream and error output stream
        System.setOut(printStream);

        SearchAlgorithm searchAlgorithm = new SearchAlgorithm();
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("hh-mm-ss dd MM yyyy");

        String pathFileError = savePathFile.getText() + " " + dateFormat.format(date) + ".txt";

        Thread thread = new Thread(() -> {
            searchAlgorithm.searchProduct(openPathFile.getText(), pathFileError, Integer.parseInt(reductionPrice.getText()));
            modifyPrice.setText("Chỉnh Giá");
            modifyPrice.setEnabled(true);
        });
        thread.start();
//        SwingUtilities.invokeLater(() -> {
//            searchAlgorithm.searchProduct(openPathFile.getText(), pathFileError, Integer.parseInt(reductionPrice.getText()));
//        });
        
    }//GEN-LAST:event_modifyPriceActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileText;
        fileText = new JFileChooser();
        FileFilter fileFilter = new FileNameExtensionFilter("*.txt", "txt");
        fileText.addChoosableFileFilter(fileFilter);
        fileText.setFileFilter(fileFilter);
        int i = fileText.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            openPathFile.setText(fileText.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileText;
        fileText = new JFileChooser();
        FileFilter fileFilter = new FileNameExtensionFilter("*.txt", "txt");
        fileText.addChoosableFileFilter(fileFilter);
        fileText.setFileFilter(fileFilter);
        int i = fileText.showSaveDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            savePathFile.setText(fileText.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void reductionPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reductionPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reductionPriceActionPerformed

    private void reductionPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reductionPriceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_reductionPriceKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrontEndSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrontEndSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrontEndSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrontEndSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new FrontEndSearch().setVisible(true);
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JTextArea displayResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyPrice;
    private javax.swing.JButton openFileButton;
    private javax.swing.JTextField openPathFile;
    private javax.swing.JTextField reductionPrice;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JTextField savePathFile;
    // End of variables declaration//GEN-END:variables
}
